import Head from "next/head";
import SignIn from "../components/SignIn";

export default function Home() {
  return (
    <>
      <Head>
        <title>GitHub Client Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/github.svg" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <SignIn />
    </>
  );
}
